# Generated by Django 5.1 on 2024-09-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="eventonombre",
            new_name="titulo",
        ),
        migrations.AlterField(
            model_name="organizador",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
